### ISSUE TITLE
Can't launch the application

### ISSUE THREAD

**Issue by Gipson62** [FearNixx/vigilant-bans#14]
Hello, sorry to bother you, but I would like to use your application, I downloaded the .zip and extracted it, installed Java version 17 and installed Node.js too. When I run the .bat as said in the "tutorial", I get a powershell screen with scrolling text, then it closes and nothing. What does he do for it? I tried with versions 1.0.2, 1.0.3 and 1.0.4.

(I'm using Google translate, so i'm sorry for the spelling mistake)

**Comment by MarkTwoFive** [comment]
Hi,

firstly, you only need to install Java 17. The application downloads a portable installation of NodeJS on its own.

Secondly, you can see the console output by starting the application using the Windows terminal.
To do that...
- open a command prompt (just search "cmd" in Windows).
- Paste the path to the ``.bat`` file from vigilant bans.
- Press "Enter".
- After the log output ran through, the prompt will stay open and you can read or screenshot the log output.

**Comment by Gipson62** [comment]
Thx, I'm going to do that, and for Nodejs I've already the version cuz I needed it for a JavaScript project

**Comment by Gipson62** [comment]
This is the first error message I received in the command prompt, I installed Java 17 with the link in your description


![image](https://user-images.githubusercontent.com/70176484/171842929-627cea1f-5b1a-4fd1-b7c7-5b13eaccb12c.png)

**Comment by MarkTwoFive** [comment]
Interesting error message 🤔  Can you please provide some more information on your system? From the error message, it seems like your CPU platform architecture might not  be supported by OpenJFX.

**Comment by Gipson62** [comment]
I'm using a Lenovo Ideapad Gaming 3 15IMH05 and here are the specs :
![image](https://user-images.githubusercontent.com/70176484/172453297-b4d76821-17f0-4b5e-b468-d050ceec3e6c.png)

I can retry to install java if u think it's necessary 🤔

**Comment by MarkTwoFive** [comment]
Those specs look fine - the CPU is 64-bit. Next thing to check would in fact be Java. Make sure that the 64-bit version of Java is installed and the default version for your system. (You should not need any modern Java Version in 32-bit anyways.)

**Comment by Gipson62** [comment]
Hello,

I just reinstall the same java, and now I think that works fine. I don't understand Windows at all. Yesterday I needed 3 installations of scons to made him work.

**Comment by MarkTwoFive** [comment]
Weird, but in that case - glad it works now.
