### ISSUE TITLE
Install startet nicht

### ISSUE THREAD

**Issue by BigSaVo** [FearNixx/vigilant-bans#15]
Hello,
I previously downloaded and unpacked version 1.0.4. But unfortunately the install doesn't start. As soon as I start the vigilant-bans.bat, the CMD opens briefly and closes again immediately. Unfortunately, you can't open anything :-(

**Comment by MarkTwoFive** [comment]
Hi,

you can see the console output by starting the application using the Windows terminal.
To do that...
- open a command prompt (just search "cmd" in Windows).
- Paste the path to the ``.bat`` file from vigilant bans.
- Press "Enter".
- After the log output ran through, the prompt will stay open and you can read or screenshot the log output.

**Comment by BigSaVo** [comment]
![grafik](https://user-images.githubusercontent.com/77449760/174447343-d9823616-7b2d-4d2b-97f7-23fa79e5df38.png)

I did that with the powershell which hopefully was okay

**Comment by BigSaVo** [comment]
I have now tested version 1.0.3. It runs so far. But as soon as you close the program and start it again, you want to reinstall everything. It doesn't recognize the existing installation

**Comment by MarkTwoFive** [comment]
You're running an outdated version of Java :)
1.0.4 requires Java 17 or later.

**Comment by BigSaVo** [comment]
Hey vielen dank für deine Hilfe klappt alles jetzt.
Jetzt ist nur noch die frage wie kann ich das Layout simple aktivieren?

**Comment by MarkTwoFive** [comment]
Gern geschehen.

Von vigilant-bans aus lässt sich das verwendete Layout nicht umschalten. Bisher hat diese Funktion niemand benötigt.
Es wurde entweder das EU-Layout im Originalzustand verwendet, oder entsprechende Anpassungen daran vorgenommen. 🤔

**Comment by BigSaVo** [comment]
Okay schade. Ich hätte das gerne verwendet und hatte gehofft das man vielleicht nur, was bei der style.css was umstellen bräuchte. Da meine Kenntnisse leider dazu nicht vorhanden sind ohne Hilfe das umzuändern.

**Comment by MarkTwoFive** [comment]
- Not a bug
- Feature request in #16
