### ISSUE TITLE
Config file is empty, when you leave the score empty in config settings.

### ISSUE THREAD

**Issue by Kenai-Lama** [FearNixx/vigilant-bans#17]
This is a nice tool, but I want you to be aware of a bug I found:

When I change the configs and leave one (or both) of the scores empty, the content of the config file in the pick & ban tool is deleted, so the file is empty.

Screenshots of the thrown exceptions:
![grafik](https://user-images.githubusercontent.com/77550792/174892896-14dc6fd3-d0ce-49a4-9c09-ac3e5923e582.png)
![grafik](https://user-images.githubusercontent.com/77550792/174892951-e4bbe790-d99d-4c97-bd9c-c86f7d0d109f.png)

I searched a bit in the Code and I think you need to catch the `NumberFormatException` while parsing the score in [ConfigFX.java#L173](https://github.com/FearNixx/vigilant-bans/blob/master/src/main/java/de/fearnixx/lolbanpick/config/ConfigFX.java#L173) and [ConfigFX.java#L179](https://github.com/FearNixx/vigilant-bans/blob/master/src/main/java/de/fearnixx/lolbanpick/config/ConfigFX.java#L179) and maybe write a default value (0) into it instead.

Since the only way to fix the tool, after one made the mistake of leaving it blank (or writing some non number text into it) is to copy the config from a running version into the broken one, the bug seems critical too me.

**Comment by MarkTwoFive** [comment]
Hi,

thanks for the submission.
I'll add a sanity check that'll be included whenever the next release is.

However, I wouldn't consider this critical because having no score at all does not logically make sense.  
It's fairly normal for competitions to start at 0 - 0.
