### ISSUE TITLE
If the team name is written in Korean, it will appear as '?'.

### ISSUE THREAD

**Issue by sod101316** [FearNixx/vigilant-bans#18]
If the team name is written in Korean, it will appear as '?'. However, the player's Korean nickname is good.
How can i fix it?
![Screenshot 2022-06-27 015101](https://user-images.githubusercontent.com/59684822/175825093-80c91478-feb7-4205-991c-2cf870c161cf.png)

**Comment by MarkTwoFive** [comment]
Hi and thanks for the report,

maybe there's an issue with the encoding used in the configuration.
I will take a look into this but this might be an issue with the upstream project for all I know right now.

**Comment by MarkL4YG** [comment]
Hi,

can you please try out this build:
[vigilant-bans-1.0.4-SNAPSHOT.zip](https://github.com/FearNixx/vigilant-bans/files/9012727/vigilant-bans-1.0.4-SNAPSHOT.zip)

I've forced the application to read and write the banpick configuration file using UTF-8 encoding which should support those characters.

**Comment by MarkTwoFive** [comment]
Hi,

can you please try out this build:
[vigilant-bans-1.0.4-SNAPSHOT.zip](https://github.com/FearNixx/vigilant-bans/files/9012747/vigilant-bans-1.0.4-SNAPSHOT.zip)

I've forced the application to read and write the banpick configuration file using UTF-8 encoding which should support those characters.
