### ISSUE TITLE
I don't understand why my champion image is error?

### ISSUE THREAD

**Issue by ThanhNam-dev** [FearNixx/vigilant-bans#19]
I did all the steps according to the correct procedure, but when it was time to ban pick champion, the system displayed the champion image is error.
How can i fix it?
![pick](https://user-images.githubusercontent.com/56708781/216892035-9ae763c6-7802-4432-a0e9-909da6ca7769.png)

**Comment by MarkTwoFive** [comment]
Hi 👋🏼 ,
I'm not sure what could be causing this issue. Please consult the ban-picks project for that as they maintain the overlay.
