### ISSUE TITLE
SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by jordanisapple1999** [FearNixx/vigilant-bans#2]
connect
http://localhost:3000/frontend-lib.js:83:23
PB.start
http://localhost:3000/frontend-lib.js:110:5
(anonymous function)
C:/lol-pick-ban-ui-master/lol-pick-ban-ui-master/layouts/layout-volu-europe/src/App.jsx:38
  35 |         setConfig(hb.config);
  36 |     });
  37 | 
> 38 |     Window.PB.start();
     | ^  39 | }, []);
  40 | 
  41 | console.log(globalState);
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
![image](https://user-images.githubusercontent.com/67945889/111579818-43d38f00-87e9-11eb-8160-9de75b010ef7.png)

**Comment by jordanisapple1999** [comment]
I hope you can help soon!!!

**Comment by MarkTwoFive** [comment]
Hi 👋 

the error appears to be from the pick-ban-tool itself and not directly related to this project.  
I assume, you're seeing this error in your browser?  
Please make sure to start the involved applications in this order:
1. LoL-Client
2. LCU-Broker (wait for it to be ready - there should be a corresponding message in the console)
3. Overlay (this will also tell you, when it's ready)

If that still doesn't work, please elaborate more on what you're doing, what you're expecting to happen and what actually happens so we can try to reproduce the issue.

**Comment by Hebelag** [comment]
This error will always come after executing "npm start" inside the layout folder powershell. Just follow the step-by-step installation and in the end you should put http://localhost:3000/?backend=ws://localhost:8999 instead of only localhost:3000

**Comment by MarkTwoFive** [comment]
> This error will always come after executing "npm start" inside the layout folder powershell.

If you're manually executing NPM commands when using this project, you're using it wrongly. The project is designed to do that for you. 

> Just follow the step-by-step installation and in the end you should put http://localhost:3000/?backend=ws://localhost:8999 instead of only localhost:3000

If you take a look [here](https://github.com/FearNixx/vigilant-bans/blob/master/src/main/java/de/fearnixx/lolbanpick/Constants.java#L29), you'll see we're indeed using that URL when you use vigilant-bans.

**Comment by MarkTwoFive** [comment]
Since I did not receive any further response, I'm going to assume the issue has been resolved.  
Feel free to re-open if the issue still persists.
