### ISSUE TITLE
Adding Color Control?

### ISSUE THREAD

**Issue by exr** [FearNixx/vigilant-bans#3]
Is it possible to add custom colors (as the config provides) and even better one button in the middle to swap teams and a second one to swap color?
As I for myself use custom colors themed for the org I'm streaming matches for. And I'll always want to have the custom color fitting to which side my team is playing at.

If those options could be added, I'd use your GUI instantly. But so far I need to manually change the config I guess :P

**Comment by MarkTwoFive** [comment]
Hi 👋 
As you already noticed, the team color control is already prepared but currently disabled. Since you took the time to create an issue for this, I'll take the time to implement that now 😄   
As for having a "swap" button, that shouldn't be that difficult either so I'll take a look at that too.

**Comment by exr** [comment]
> Hi 👋
> As you already noticed, the team color control is already prepared but currently disabled. Since you took the time to create an issue for this, I'll take the time to implement that now 😄
> As for having a "swap" button, that shouldn't be that difficult either so I'll take a look at that too.

Yep I've seen those RGB boxes already ;D
That would be super nice! 😅

Maybe add a check box below the swap button so that one could choose to swap colors aswell or let them be? 🤔

**Comment by MarkTwoFive** [comment]
// Implemented 🙂 in 1.0.2

Feel free to re-open if you're not satisfied, yet.
