### ISSUE TITLE
How to start up?

### ISSUE THREAD

**Issue by KenAijmNight** [FearNixx/vigilant-bans#4]
I have download it! But have no clue or idea from the readme how to open or install or something else this project. Can the upset or installing be more specific?

**Comment by MarkTwoFive** [comment]
I understand that not everyone has technical background, but starting the application is very much described in the readme.  

> After downloading the archive (zip or tar), the application can be started using the bin/vigilant-bans.bat file.

It's really just that. Once you've downloaded and extracted the release archive, there's only this one batch file to launch and you're guided through the installation.  
  
Or are you just unfamiliar with GitHub and don't know what to download? In that case, just head over to [the releases page](https://github.com/FearNixx/vigilant-bans/releases) and download the latest ``vigilant-bans-X.X.X.zip`` (which at this time is ``vigilant-bans-1.0.2.zip``.

**Comment by MarkTwoFive** [comment]
Since I did not hear back from you, I'm going to assume this issue is resolved.
