### ISSUE TITLE
Overlay does not start

### ISSUE THREAD

**Issue by BigSaVo** [FearNixx/vigilant-bans#5]
Hello. First of all, nice work with the installation. It was very easy. Now I have the following problem. My overlay does not start in the browser. See image:

![grafik](https://user-images.githubusercontent.com/77449760/122261067-491da400-ced4-11eb-808e-9fccde171299.png)

![grafik](https://user-images.githubusercontent.com/77449760/122261116-563a9300-ced4-11eb-8917-851f7df01c0d.png)

Did everything as in the instructions
![grafik](https://user-images.githubusercontent.com/77449760/122260902-15db1500-ced4-11eb-8b27-678d4fcb72b0.png)

I would appreciate help

**Comment by NicolasM3** [comment]
This works for me:

1. Open the folder: `vigilant-bans-1.0.2\bin\cache\lol-pick-ban-ui-master\layouts\layout-volu-europe`
2. Open up a command prompt (Windows: Shift + Rightclick -> Open Powershell / Commandline Window here)
3. npm remove react-dev-utils
4. npm i react-dev-utils@10.0.0

Original answer: https://github.com/ionic-team/ionic-framework/issues/20503#issuecomment-602027266

**Comment by BigSaVo** [comment]
Hi that worked out great. Thank you very much for the quick answer. Nice greetings from Germany

**Comment by BigSaVo** [comment]
Is there a possibility to use the layout simply with the FearNixx program?

**Comment by MarkTwoFive** [comment]
> npm remove react-dev-utils
npm i react-dev-utils@10.0.0  

If this works, this might be another issue with breaking dependency updates. We already hat one with #1 that has been fixed by pinning the corresponding dependency to a version that works.

**Comment by MarkTwoFive** [comment]
> Is there a possibility to use the layout simply with the FearNixx program?

We could pin the dependency during installation. Since the other issue, there is a mechanism for this. Sadly, I don't really have time to implement and test that at the moment.

**Comment by AsukaFile** [comment]
Hey, sadly I have the same issue like BigSaVo descripted in the first place. But sadly the solution by NicolasM3 didn´t work for me. I tried to enter the command in diffrent ways but sadly my powershell doesn´t understand me. 
![Pick ban tool](https://user-images.githubusercontent.com/87932018/126896191-cee7529b-98f3-419c-8f35-a49670769e1b.png)

**Comment by MarkTwoFive** [comment]
@AsukaFile 
I've just released an [untested update](https://github.com/FearNixx/vigilant-bans/releases/tag/v1.0.3) that might fix your issue.  
Please try it and tell me whether or not it works now.
