### ISSUE TITLE
"Could not create Java Virtual Machine"

### ISSUE THREAD

**Issue by Hebelag** [FearNixx/vigilant-bans#6]
The problem is everytime I open the .bat file, it just closes again and again.
"unrecognized option --module-path
Error: Could not create Java Virtual Machine
A fatal exception has occurred."

Solution: Check your java version in the terminal with "java -version".
If it is under 9, you need to install a newer version (newest version is 16 downloadable at oracle.com)

**Comment by MarkTwoFive** [comment]
> Solution: Check your java version in the terminal with "java -version".
If it is under 9, you need to install a newer version (newest version is 16 downloadable at oracle.com)

Exactly. The software requires at least Java 11 to run. Older versions are not supported.  
We recommend the free version from [AdoptOpenJDK](https://adoptopenjdk.net)

**Comment by MarkTwoFive** [comment]
Please elaborate on what exactly you need help here. Otherwise I can only assume your issue is resolved and close the issue as invalid.

**Comment by Hebelag** [comment]
I can close the issue. I don't know why this is invalid. I thought I could help people.

**Comment by MarkTwoFive** [comment]
> I don't know why this is invalid

It is invalid, because it is not an actual issue. This software is not intended to run on any version of Java older than 11.  

> I thought I could help people.

That's still the case - closed issues would also pop up on search engines 😉
