### ISSUE TITLE
Gives me this error when I open the browser

### ISSUE THREAD

**Issue by Fivxs** [FearNixx/vigilant-bans#7]
![Screenshot_3](https://user-images.githubusercontent.com/86251096/122870995-f96e2b00-d360-11eb-9028-c46ee6800700.png)

**Comment by Fivxs** [comment]
![image](https://user-images.githubusercontent.com/86251096/122871424-8fa25100-d361-11eb-987c-1acacbe78a19.png)
It also gives this error on the CMD

**Comment by MarkTwoFive** [comment]
From this error, I cannot really see what's wrong.  
But since this error is raised in the volunteers project, I would like you to request support there instead.  
  
Currently, I sadly do not have the time to debug such issues.

**Comment by MarkTwoFive** [comment]
Nevermind - this appears to be a duplicate of #5
