### ISSUE TITLE
Can't start LCU Connector / missing the "package.json" file

### ISSUE THREAD

**Issue by FireFoXz09** [FearNixx/vigilant-bans#8]
I install everything, but when I click on the Start LCU Connector, this error appear : 

I tried to start the europe overlay first just to see if the error would be the same, and yes it is.

![image](https://user-images.githubusercontent.com/89284738/130306656-9366510a-cd2a-40fb-a830-c9e32af2bbb8.png)

Also, during the installation, it says that the package.json is missing

![image](https://user-images.githubusercontent.com/89284738/130307533-7851af05-957b-47f4-9987-c1b8b5e4c45a.png)

**Comment by MarkTwoFive** [comment]
Hi 👋 

the newest version should not have this issue, if I'm not mistaken. 🤔 
Please try to remove the tool by deleting the directories and install 1.0.2 to see if the issue persists.

**Comment by DiegoLugo** [comment]
Still persists with latest version

**Comment by DiegoLugo** [comment]
V1.0.3 fixed this issue and now prompts errors because it always tries to connect to the league client

**Comment by MarkTwoFive** [comment]
> always tries to connect to the league client

The LCU connector does that for as long as it is running. If you close the client, you can also stop the connector in the tool to prevent these errors from popping up.

**Comment by MarkTwoFive** [comment]
Closed because I'm considering this to be resolved.
